insert into public.writing_prompts (
  id,
  task_type,
  title,
  topic,
  difficulty,
  duration_minutes,
  minimum_words,
  brief,
  instructions,
  planning_checklist,
  is_active,
  source
)
values
(
  'task2-remote-work',
  'Task 2',
  'Remote work and employee productivity',
  'Work and society',
  'Balanced',
  40,
  250,
  'Some people believe remote work improves productivity, while others think employees work better in an office. Discuss both views and give your own opinion.',
  '["Present both views in a balanced way before giving your final position.","Support your opinion with clear reasons and practical examples.","Aim for a focused four-paragraph structure."]'::jsonb,
  '["Clarify your position before you begin writing.","Write one body paragraph for each side of the argument.","Use a short conclusion that reinforces your opinion."]'::jsonb,
  true,
  'seed'
),
(
  'task2-ai-education',
  'Task 2',
  'AI tools in school education',
  'Education and technology',
  'Stretch',
  40,
  250,
  'Schools are increasingly using AI tools to support teaching and learning. Do the advantages outweigh the disadvantages?',
  '["State a clear overall judgement early in the essay.","Explain both the opportunities and the risks of AI in education.","Keep examples realistic and directly connected to the main point."]'::jsonb,
  '["Decide whether your essay is mainly positive, negative, or balanced.","Use topic sentences to make the argument easy to follow.","Avoid listing ideas without explaining their impact."]'::jsonb,
  true,
  'seed'
),
(
  'task1-cycle-diagram',
  'Task 1',
  'Water recycling process',
  'Process diagram',
  'Guided',
  20,
  150,
  'The diagram shows the stages used to recycle water in a modern city. Summarize the information by selecting and reporting the main features.',
  '["Write an overview that identifies the start and end of the cycle.","Group related stages together instead of describing every step in isolation.","Use precise process language and sequencing connectors."]'::jsonb,
  '["Write a one-sentence overview before the detailed description.","Move through the process in a logical order.","Check verb tenses and passive voice choices."]'::jsonb,
  true,
  'seed'
),
(
  'task2-public-transport-funding',
  'Task 2',
  'Public transport funding',
  'Urban change and transport',
  'Guided',
  40,
  250,
  'Some people think governments should make public transport free to reduce traffic congestion. Others believe this is too expensive. Discuss both views and give your opinion.',
  '["Explain the traffic and cost sides of the argument.","Give a clear final position instead of staying neutral throughout.","Use examples connected to cities, commuters, or public budgets."]'::jsonb,
  '["Decide whether the public benefit is worth the financial cost.","Plan one paragraph about congestion and one about funding limits.","Make the conclusion answer the question directly."]'::jsonb,
  true,
  'seed'
),
(
  'task2-health-advertising',
  'Task 2',
  'Advertising and unhealthy lifestyles',
  'Health and lifestyle',
  'Balanced',
  40,
  250,
  'Many advertisements encourage people to buy unhealthy food and drinks. Should governments restrict this type of advertising?',
  '["State whether restriction is necessary, excessive, or partly justified.","Explain the public health impact and the freedom-of-choice concern.","Use a realistic policy example rather than a vague claim."]'::jsonb,
  '["Choose a clear position on government restriction.","Separate health consequences from personal responsibility.","Add one example about children, hospitals, or consumer habits."]'::jsonb,
  true,
  'seed'
),
(
  'task2-environment-responsibility',
  'Task 2',
  'Environmental responsibility',
  'Environment and climate',
  'Balanced',
  40,
  250,
  'Some people believe individuals should take responsibility for protecting the environment, while others think governments and companies have the greatest responsibility. Discuss both views and give your opinion.',
  '["Compare individual habits with large-scale policy and business decisions.","Avoid claiming that only one group matters.","Support the final opinion with cause-and-effect explanation."]'::jsonb,
  '["Plan one paragraph for individual behavior and one for institutions.","Use concrete examples such as transport, waste, or energy.","Show why your chosen side has greater impact."]'::jsonb,
  true,
  'seed'
),
(
  'task2-automation-jobs',
  'Task 2',
  'Automation and future jobs',
  'Work and society',
  'Stretch',
  40,
  250,
  'Automation is replacing some types of work. Do you think this change creates more opportunities or more problems for society?',
  '["Take a clear position on the overall impact of automation.","Discuss both job loss and new forms of work or productivity.","Keep examples specific enough to show real-world understanding."]'::jsonb,
  '["Decide whether opportunity or risk is stronger overall.","Use one paragraph for economic benefits and one for worker disruption.","End with a practical judgement about retraining or policy support."]'::jsonb,
  true,
  'seed'
),
(
  'task2-social-media-news',
  'Task 2',
  'Social media as a news source',
  'Education and technology',
  'Stretch',
  40,
  250,
  'More people now get news from social media rather than traditional newspapers or television. Is this a positive or negative development?',
  '["Judge the development clearly instead of listing only advantages and disadvantages.","Explain speed and accessibility alongside misinformation risks.","Use examples about media literacy, public debate, or trust."]'::jsonb,
  '["Choose whether the overall effect is positive, negative, or mixed.","Plan one paragraph about access and one about reliability.","Make the final answer connect to informed decision-making."]'::jsonb,
  true,
  'seed'
),
(
  'task1-city-centre-map',
  'Task 1',
  'City centre redevelopment map',
  'Urban change and transport',
  'Balanced',
  20,
  150,
  'The maps show changes to a city centre between 2000 and 2025. Summarize the information by selecting and reporting the main features.',
  '["Introduce the two maps without giving opinions.","Highlight the biggest land-use and transport changes in the overview.","Group details by area of the city rather than listing every building."]'::jsonb,
  '["Identify what was added, removed, or relocated.","Write an overview about the overall direction of redevelopment.","Use past and present perfect forms accurately."]'::jsonb,
  true,
  'seed'
),
(
  'task1-energy-line-chart',
  'Task 1',
  'Household energy use trends',
  'Environment and climate',
  'Balanced',
  20,
  150,
  'The line chart compares household energy use from renewable and non-renewable sources between 2010 and 2030. Summarize the information by selecting and reporting the main features.',
  '["State the overall direction of both lines in the overview.","Compare the two sources at meaningful points instead of every year.","Use trend language accurately."]'::jsonb,
  '["Find the starting point, crossing point, and final point.","Group the description into early and later periods.","Check comparative language such as higher than and overtook."]'::jsonb,
  true,
  'seed'
),
(
  'task1-commuter-bar-chart',
  'Task 1',
  'Commuter transport choices',
  'Urban change and transport',
  'Guided',
  20,
  150,
  'The bar chart shows the percentage of commuters using cars, buses, trains, and bicycles in three cities. Summarize the information by selecting and reporting the main features.',
  '["Compare the most and least popular transport choices.","Group cities or transport types where the patterns are similar.","Avoid describing each bar in isolation."]'::jsonb,
  '["Identify the highest and lowest categories first.","Choose two comparison groups before writing.","Use percentages and comparative phrases carefully."]'::jsonb,
  true,
  'seed'
),
(
  'task1-recycling-table',
  'Task 1',
  'Recycling rates by material',
  'Environment and climate',
  'Stretch',
  20,
  150,
  'The table compares recycling rates for paper, plastic, glass, and metal in four countries in 2024. Summarize the information by selecting and reporting the main features.',
  '["Identify the strongest and weakest recycling performance.","Group materials or countries to avoid a long list of numbers.","Include only figures that support the main comparisons."]'::jsonb,
  '["Find the highest country-material combination.","Group similar rates together before drafting.","Use cautious comparison language for close figures."]'::jsonb,
  true,
  'seed'
),
(
  'task1-online-learning-pie-charts',
  'Task 1',
  'Online learning platform usage',
  'Education and technology',
  'Balanced',
  20,
  150,
  'The pie charts compare how students used online learning platforms for lectures, assignments, discussion, and revision in 2018 and 2024. Summarize the information by selecting and reporting the main features.',
  '["Compare the two years and focus on the largest proportional changes.","Write an overview that identifies the overall shift in platform usage.","Avoid over-reporting small slices unless they support the main pattern."]'::jsonb,
  '["Identify which category grew the most.","Group stable categories separately from changing categories.","Use proportion language such as share, accounted for, and declined."]'::jsonb,
  true,
  'seed'
)
on conflict (id) do update
set
  task_type = excluded.task_type,
  title = excluded.title,
  topic = excluded.topic,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  minimum_words = excluded.minimum_words,
  brief = excluded.brief,
  instructions = excluded.instructions,
  planning_checklist = excluded.planning_checklist,
  is_active = excluded.is_active,
  source = excluded.source;
